language: python
dist: xenial
sudo: false
cache:
  pip: true

matrix:
  fast_finish: true
  include:
    - python: '3.4'
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'
      name: 'Lint, Coverage'
      before_script:
        - pip install flake8 coverage
      script:
        - flake8 --max-line-length=100 .
        - time catchsegv coverage run setup.py test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

before_install:
  - set -e

install:
  - pip install .

script:
  - catchsegv python setup.py test
